#include <stdio.h>
#include <CTraderHandler.h>
#include <Configure.h>
#include <CTraderWrapper.h>
#include <unistd.h>
#include <zmq.hpp>
#include <zhelpers.hpp>
#include <json/json.h>
#include <comhelper.h>
#include <Message.h>
#include <chrono>
#include <iostream>
#include <queue>
